
#ifndef __CHUCK_OPERATORS_H__
#define __CHUCK_OPERATORS_H__

enum {
    CHUCK_OP_CHUCK,
    CHUCK_OP_UN_CHUCK,
    CHUCK_OP_UP_CHUCK,
    CHUCK_OP_RSHIFT_CHUCK,
    CHUCK_OP_LSHIFT_CHUCK,
    CHUCK_OP_MINUS_CHUCK,
    CHUCK_OP_PLUS_CHUCK,
    CHUCK_OP_DIV_CHUCK,
    CHUCK_OP_MOD_CHUCK,
    CHUCK_OP_TIMES_CHUCK,
    CHUCK_OP_BIT_AND_CHUCK,
    CHUCK_OP_BIT_OR_CHUCK,
    CHUCK_OP_BIT_XOR_CHUCK,
    CHUCK_OP_BIT_NOT_CHUCK,
    CHUCK_OP_AT_CHUCK,
    CHUCK_OP_NOT_CHUCK,

    CHUCK_OP_BIT_NOT,
    CHUCK_OP_NOT,
    CHUCK_OP_PLUSPLUS,
    CHUCK_OP_MINUSMINUS,

    CHUCK_OP_PLUS,
    CHUCK_OP_MINUS,
    CHUCK_OP_DIVIDE,
    CHUCK_OP_TIMES,
    CHUCK_OP_PERCENT,
    CHUCK_OP_POWER,

    CHUCK_OP_BIT_OR,
    CHUCK_OP_BIT_AND,
    CHUCK_OP_BIT_XOR,
    CHUCK_OP_LSHIFT,
    CHUCK_OP_RSHIFT,

    CHUCK_OP_CMP_LE,
    CHUCK_OP_CMP_LT,
    CHUCK_OP_CMP_EQ,
    CHUCK_OP_CMP_NE,
    CHUCK_OP_CMP_GT,
    CHUCK_OP_CMP_GE,

    CHUCK_OP_LOG_AND,
    CHUCK_OP_LOG_OR,
    CHUCK_OP_LOG_XOR,
};

#endif
