

#ifndef __CHUCK_SCANNER_H__
#define __CHUCK_SCANNER_H__

#if defined(_cplusplus) || defined(__cplusplus)
extern "C" {
#endif

#include "chuck_fwddefs.h"

// Refine this based on how many tokens are generated by the parser.
#define MAX_TOKENS  200

struct ChuckScanner
{
    CUIStream *instream;
    uchar *bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint line;
    ChuckToken currToken;
};

extern ChuckScanner *chuck_scanner_create(CUIStream *instream);
extern void chuck_scanner_destroy(ChuckScanner *scanner);
extern int chuck_scanner_scan(ChuckScanner *scanner);
extern const char *chuck_scanner_token_string(int token);

#if defined(_cplusplus) || defined(__cplusplus)
}
#endif

#endif

