/* Generated by re2c 0.13.5 on Wed Oct  2 07:36:46 2013 */
#line 1 "scanner.re2c"

#include "chuck.h"

#define    BSIZE    8192
#define YYCTYPE char
#define YYCURSOR cursor
#define YYLIMIT scanner->lim
#define YYMARKER scanner->ptr
#define YYFILL(n) {cursor = fill(scanner, cursor); }

int prepare_token_value(int tokValue, ChuckScanner *scanner)
{
    char bak = *scanner->cur;
    scanner->cur[0] = 0;
    if (tokValue == TOKEN_DOUBLE)
    {
        scanner->currToken.value.doubleValue = atof((const char *)scanner->tok);
    }
    else if (tokValue == TOKEN_LONG)
    {
        scanner->currToken.value.longValue = atol((const char *)scanner->tok);
    }
    else if (tokValue == TOKEN_IDENTIFIER)
    {
        scanner->currToken.value.stringValue = cu_string((const char *)scanner->tok);
    }
    else if (tokValue == TOKEN_STRING)
    {
        int len = (scanner->cur - 1) - (scanner->tok + 1);
        if (len < 0) len = 0;
        scanner->currToken.value.stringValue = cu_string_from_buffer((const char *)scanner->tok + 1, len);
    }
    scanner->cur[0] = bak;
    scanner->currToken.tokenType = tokValue;
    return tokValue;
}

#define RET(tokvalue) { scanner->cur = cursor; return prepare_token_value(tokvalue, scanner); }

ChuckScanner *chuck_scanner_create(CUIStream *instream)
{
    ChuckScanner *scanner = ZNEW(ChuckScanner);
    cu_setattr(scanner, instream, instream);
    return scanner;
}

void chuck_scanner_destroy(ChuckScanner *scanner)
{
    if (scanner->instream)
    {
        cu_stream_close(scanner->instream);
        cu_setattr(scanner, instream, NULL);
    }
    free(scanner);
}

uchar *fill(ChuckScanner *scanner, uchar *cursor){
    if(!scanner->eof) {
        uint cnt = scanner->tok - scanner->bot;
        if(cnt){
            memcpy(scanner->bot, scanner->tok, scanner->lim - scanner->tok);
            scanner->tok = scanner->bot;
            scanner->ptr -= cnt;
            cursor -= cnt;
            scanner->pos -= cnt;
            scanner->lim -= cnt;
        }
        if((scanner->top - scanner->lim) < BSIZE){
            uchar *buf = (uchar*) malloc(((scanner->lim - scanner->bot) + BSIZE)*sizeof(uchar));
            memcpy(buf, scanner->tok, scanner->lim - scanner->tok);
            scanner->tok = buf;
            scanner->ptr = &buf[scanner->ptr - scanner->bot];
            cursor = &buf[cursor - scanner->bot];
            scanner->pos = &buf[scanner->pos - scanner->bot];
            scanner->lim = &buf[scanner->lim - scanner->bot];
            scanner->top = &scanner->lim[BSIZE];
            free(scanner->bot);
            scanner->bot = buf;
        }
        if ((cnt = cu_istream_read(scanner->instream, (char*) scanner->lim, BSIZE)) != BSIZE){
            scanner->eof = &scanner->lim[cnt]; *(scanner->eof)++ = '\n';
        }
        scanner->lim += cnt;
    }
    return cursor;
}

int chuck_scanner_scan(ChuckScanner *scanner)
{
    uchar *cursor = scanner->cur;
std:
    scanner->tok = cursor;
#line 103 "scanner.re2c"



#line 100 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy72;
	case '\n':	goto yy74;
	case '!':	goto yy44;
	case '"':	goto yy9;
	case '#':	goto yy30;
	case '$':	goto yy38;
	case '%':	goto yy36;
	case '&':	goto yy50;
	case '\'':	goto yy5;
	case '(':	goto yy56;
	case ')':	goto yy58;
	case '*':	goto yy34;
	case '+':	goto yy26;
	case ',':	goto yy32;
	case '-':	goto yy28;
	case '.':	goto yy7;
	case '/':	goto yy10;
	case '0':	goto yy2;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy4;
	case ':':	goto yy42;
	case ';':	goto yy40;
	case '<':	goto yy46;
	case '=':	goto yy43;
	case '>':	goto yy48;
	case '@':	goto yy70;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'q':
	case 't':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy25;
	case '[':	goto yy60;
	case ']':	goto yy62;
	case '^':	goto yy54;
	case 'b':	goto yy16;
	case 'c':	goto yy15;
	case 'd':	goto yy21;
	case 'e':	goto yy23;
	case 'f':	goto yy17;
	case 'i':	goto yy22;
	case 'n':	goto yy24;
	case 'p':	goto yy12;
	case 'r':	goto yy18;
	case 's':	goto yy14;
	case 'u':	goto yy20;
	case 'w':	goto yy19;
	case '{':	goto yy64;
	case '|':	goto yy52;
	case '}':	goto yy66;
	case '~':	goto yy68;
	default:	goto yy76;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy267;
	case 'X':
	case 'x':	goto yy284;
	default:	goto yy283;
	}
yy3:
#line 106 "scanner.re2c"
	{ RET(TOKEN_LONG); }
#line 222 "scanner.c"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy265;
yy5:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':
	case '\r':	goto yy6;
	default:	goto yy255;
	}
yy6:
#line 196 "scanner.re2c"
	{
        if (cursor >= scanner->eof) { RET(TOKEN_EOI); }
        else { RET(TOKEN_ERROR); }
    }
#line 241 "scanner.c"
yy7:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy246;
	default:	goto yy8;
	}
yy8:
#line 139 "scanner.re2c"
	{ RET(TOKEN_DOT); }
#line 260 "scanner.c"
yy9:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':
	case '\r':	goto yy6;
	default:	goto yy237;
	}
yy10:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '*':	goto yy232;
	case '/':	goto yy230;
	case '=':	goto yy229;
	default:	goto yy11;
	}
yy11:
#line 143 "scanner.re2c"
	{ RET(TOKEN_DIVIDE); }
#line 281 "scanner.c"
yy12:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'u':	goto yy223;
	default:	goto yy145;
	}
yy13:
#line 132 "scanner.re2c"
	{ RET(TOKEN_IDENTIFIER); }
#line 291 "scanner.c"
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy212;
	case 't':	goto yy213;
	default:	goto yy145;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy196;
	case 'o':	goto yy197;
	default:	goto yy145;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy191;
	default:	goto yy145;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy185;
	case 'u':	goto yy186;
	default:	goto yy145;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy174;
	default:	goto yy145;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy169;
	default:	goto yy145;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy164;
	default:	goto yy145;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy162;
	default:	goto yy145;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy160;
	default:	goto yy145;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy149;
	case 'x':	goto yy150;
	default:	goto yy145;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy146;
	default:	goto yy145;
	}
yy25:
	yych = *++YYCURSOR;
	goto yy145;
yy26:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy140;
	case '=':	goto yy139;
	default:	goto yy27;
	}
yy27:
#line 140 "scanner.re2c"
	{ RET(TOKEN_PLUS); }
#line 376 "scanner.c"
yy28:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy135;
	case '=':	goto yy134;
	default:	goto yy29;
	}
yy29:
#line 141 "scanner.re2c"
	{ RET(TOKEN_MINUS); }
#line 388 "scanner.c"
yy30:
	++YYCURSOR;
#line 136 "scanner.re2c"
	{ RET(TOKEN_HASH); }
#line 393 "scanner.c"
yy32:
	++YYCURSOR;
#line 138 "scanner.re2c"
	{ RET(TOKEN_COMMA); }
#line 398 "scanner.c"
yy34:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy131;
	default:	goto yy35;
	}
yy35:
#line 142 "scanner.re2c"
	{ RET(TOKEN_TIMES); }
#line 409 "scanner.c"
yy36:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy128;
	default:	goto yy37;
	}
yy37:
#line 144 "scanner.re2c"
	{ RET(TOKEN_PERCENT); }
#line 420 "scanner.c"
yy38:
	++YYCURSOR;
#line 145 "scanner.re2c"
	{ RET(TOKEN_DOLLAR); }
#line 425 "scanner.c"
yy40:
	++YYCURSOR;
#line 147 "scanner.re2c"
	{ RET(TOKEN_SEMICOLON); }
#line 430 "scanner.c"
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy126;
	default:	goto yy6;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '<':	goto yy120;
	case '=':	goto yy124;
	case '>':	goto yy122;
	case '^':	goto yy118;
	default:	goto yy6;
	}
yy44:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy114;
	default:	goto yy45;
	}
yy45:
#line 170 "scanner.re2c"
	{ RET(TOKEN_NOT); }
#line 455 "scanner.c"
yy46:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '<':	goto yy105;
	case '=':	goto yy107;
	default:	goto yy47;
	}
yy47:
#line 151 "scanner.re2c"
	{ RET(TOKEN_CMP_LT); }
#line 466 "scanner.c"
yy48:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy98;
	case '>':	goto yy96;
	default:	goto yy49;
	}
yy49:
#line 152 "scanner.re2c"
	{ RET(TOKEN_CMP_GT); }
#line 477 "scanner.c"
yy50:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '&':	goto yy92;
	case '=':	goto yy91;
	default:	goto yy51;
	}
yy51:
#line 157 "scanner.re2c"
	{ RET(TOKEN_BIT_AND); }
#line 489 "scanner.c"
yy52:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy86;
	case '|':	goto yy87;
	default:	goto yy53;
	}
yy53:
#line 158 "scanner.re2c"
	{ RET(TOKEN_BIT_OR); }
#line 501 "scanner.c"
yy54:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy83;
	default:	goto yy55;
	}
yy55:
#line 159 "scanner.re2c"
	{ RET(TOKEN_BIT_XOR); }
#line 512 "scanner.c"
yy56:
	++YYCURSOR;
#line 164 "scanner.re2c"
	{ RET(TOKEN_LPAREN); }
#line 517 "scanner.c"
yy58:
	++YYCURSOR;
#line 165 "scanner.re2c"
	{ RET(TOKEN_RPAREN); }
#line 522 "scanner.c"
yy60:
	++YYCURSOR;
#line 166 "scanner.re2c"
	{ RET(TOKEN_LSQUARE); }
#line 527 "scanner.c"
yy62:
	++YYCURSOR;
#line 167 "scanner.re2c"
	{ RET(TOKEN_RSQUARE); }
#line 532 "scanner.c"
yy64:
	++YYCURSOR;
#line 168 "scanner.re2c"
	{ RET(TOKEN_LBRACE); }
#line 537 "scanner.c"
yy66:
	++YYCURSOR;
#line 169 "scanner.re2c"
	{ RET(TOKEN_RBRACE); }
#line 542 "scanner.c"
yy68:
	++YYCURSOR;
#line 171 "scanner.re2c"
	{ RET(TOKEN_TILDE); }
#line 547 "scanner.c"
yy70:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy79;
	default:	goto yy71;
	}
yy71:
#line 188 "scanner.re2c"
	{ RET(TOKEN_AT); }
#line 558 "scanner.c"
yy72:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy78;
yy73:
#line 190 "scanner.re2c"
	{ goto std; }
#line 566 "scanner.c"
yy74:
	++YYCURSOR;
#line 191 "scanner.re2c"
	{
        if (cursor >= scanner->eof) { RET(TOKEN_EOI); }
        scanner->pos = cursor; scanner->line++;
        goto std;
    }
#line 575 "scanner.c"
yy76:
	yych = *++YYCURSOR;
	goto yy6;
yy77:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy78:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy77;
	default:	goto yy73;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy81;
	default:	goto yy80;
	}
yy80:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy6;
	case 2: 	goto yy11;
	case 3: 	goto yy27;
	case 4: 	goto yy29;
	case 5: 	goto yy35;
	case 6: 	goto yy37;
	case 7: 	goto yy51;
	case 8: 	goto yy53;
	case 9: 	goto yy55;
	case 10: 	goto yy71;
	case 11: 	goto yy97;
	case 12: 	goto yy106;
	case 13: 	goto yy248;
	}
yy81:
	++YYCURSOR;
#line 177 "scanner.re2c"
	{ RET(TOKEN_AT_CHUCK); }
#line 620 "scanner.c"
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy84;
	default:	goto yy80;
	}
yy84:
	++YYCURSOR;
#line 184 "scanner.re2c"
	{ RET(TOKEN_BIT_XOR_CHUCK); }
#line 631 "scanner.c"
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy89;
	default:	goto yy80;
	}
yy87:
	++YYCURSOR;
#line 156 "scanner.re2c"
	{ RET(TOKEN_LOG_OR); }
#line 642 "scanner.c"
yy89:
	++YYCURSOR;
#line 183 "scanner.re2c"
	{ RET(TOKEN_BIT_OR_CHUCK); }
#line 647 "scanner.c"
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy94;
	default:	goto yy80;
	}
yy92:
	++YYCURSOR;
#line 155 "scanner.re2c"
	{ RET(TOKEN_LOG_AND); }
#line 658 "scanner.c"
yy94:
	++YYCURSOR;
#line 182 "scanner.re2c"
	{ RET(TOKEN_BIT_AND_CHUCK); }
#line 663 "scanner.c"
yy96:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy102;
	case '>':	goto yy100;
	default:	goto yy97;
	}
yy97:
#line 162 "scanner.re2c"
	{ RET(TOKEN_RSHIFT); }
#line 675 "scanner.c"
yy98:
	++YYCURSOR;
#line 154 "scanner.re2c"
	{ RET(TOKEN_CMP_GE); }
#line 680 "scanner.c"
yy100:
	++YYCURSOR;
#line 161 "scanner.re2c"
	{ RET(TOKEN_GTGTGT); }
#line 685 "scanner.c"
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy103;
	default:	goto yy80;
	}
yy103:
	++YYCURSOR;
#line 185 "scanner.re2c"
	{ RET(TOKEN_RSHIFT_CHUCK); }
#line 696 "scanner.c"
yy105:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '<':	goto yy109;
	case '=':	goto yy111;
	default:	goto yy106;
	}
yy106:
#line 163 "scanner.re2c"
	{ RET(TOKEN_LSHIFT); }
#line 708 "scanner.c"
yy107:
	++YYCURSOR;
#line 153 "scanner.re2c"
	{ RET(TOKEN_CMP_LE); }
#line 713 "scanner.c"
yy109:
	++YYCURSOR;
#line 160 "scanner.re2c"
	{ RET(TOKEN_LTLTLT); }
#line 718 "scanner.c"
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy112;
	default:	goto yy80;
	}
yy112:
	++YYCURSOR;
#line 186 "scanner.re2c"
	{ RET(TOKEN_LSHIFT_CHUCK); }
#line 729 "scanner.c"
yy114:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy116;
	default:	goto yy115;
	}
yy115:
#line 150 "scanner.re2c"
	{ RET(TOKEN_CMP_NE); }
#line 739 "scanner.c"
yy116:
	++YYCURSOR;
#line 175 "scanner.re2c"
	{ RET(TOKEN_NOT_CHUCK); }
#line 744 "scanner.c"
yy118:
	++YYCURSOR;
#line 176 "scanner.re2c"
	{ RET(TOKEN_UP_CHUCK); }
#line 749 "scanner.c"
yy120:
	++YYCURSOR;
#line 174 "scanner.re2c"
	{ RET(TOKEN_UN_CHUCK); }
#line 754 "scanner.c"
yy122:
	++YYCURSOR;
#line 173 "scanner.re2c"
	{ RET(TOKEN_CHUCK); }
#line 759 "scanner.c"
yy124:
	++YYCURSOR;
#line 149 "scanner.re2c"
	{ RET(TOKEN_CMP_EQ); }
#line 764 "scanner.c"
yy126:
	++YYCURSOR;
#line 148 "scanner.re2c"
	{ RET(TOKEN_COLONCOLON); }
#line 769 "scanner.c"
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy129;
	default:	goto yy80;
	}
yy129:
	++YYCURSOR;
#line 187 "scanner.re2c"
	{ RET(TOKEN_MOD_CHUCK); }
#line 780 "scanner.c"
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy132;
	default:	goto yy80;
	}
yy132:
	++YYCURSOR;
#line 180 "scanner.re2c"
	{ RET(TOKEN_TIMES_CHUCK); }
#line 791 "scanner.c"
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy137;
	default:	goto yy80;
	}
yy135:
	++YYCURSOR;
#line 135 "scanner.re2c"
	{ RET(TOKEN_MINUSMINUS); }
#line 802 "scanner.c"
yy137:
	++YYCURSOR;
#line 179 "scanner.re2c"
	{ RET(TOKEN_MINUS_CHUCK); }
#line 807 "scanner.c"
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy142;
	default:	goto yy80;
	}
yy140:
	++YYCURSOR;
#line 134 "scanner.re2c"
	{ RET(TOKEN_PLUSPLUS); }
#line 818 "scanner.c"
yy142:
	++YYCURSOR;
#line 178 "scanner.re2c"
	{ RET(TOKEN_PLUS_CHUCK); }
#line 823 "scanner.c"
yy144:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy145:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy13;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy147;
	default:	goto yy145;
	}
yy147:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy148;
	}
yy148:
#line 128 "scanner.re2c"
	{ RET(TOKEN_NEW); }
#line 972 "scanner.c"
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy157;
	default:	goto yy145;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy151;
	default:	goto yy145;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy152;
	default:	goto yy145;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy153;
	default:	goto yy145;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy154;
	default:	goto yy145;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy155;
	default:	goto yy145;
	}
yy155:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy156;
	}
yy156:
#line 130 "scanner.re2c"
	{ RET(TOKEN_EXTENDS); }
#line 1080 "scanner.c"
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy158;
	default:	goto yy145;
	}
yy158:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy159;
	}
yy159:
#line 125 "scanner.re2c"
	{ RET(TOKEN_ELSE); }
#line 1158 "scanner.c"
yy160:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy161;
	}
yy161:
#line 124 "scanner.re2c"
	{ RET(TOKEN_IF); }
#line 1230 "scanner.c"
yy162:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy163;
	}
yy163:
#line 122 "scanner.re2c"
	{ RET(TOKEN_DO); }
#line 1302 "scanner.c"
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy165;
	default:	goto yy145;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy166;
	default:	goto yy145;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy167;
	default:	goto yy145;
	}
yy167:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy168;
	}
yy168:
#line 121 "scanner.re2c"
	{ RET(TOKEN_UNTIL); }
#line 1392 "scanner.c"
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy170;
	default:	goto yy145;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy171;
	default:	goto yy145;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy172;
	default:	goto yy145;
	}
yy172:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy173;
	}
yy173:
#line 120 "scanner.re2c"
	{ RET(TOKEN_WHILE); }
#line 1482 "scanner.c"
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy175;
	case 't':	goto yy176;
	default:	goto yy145;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy181;
	default:	goto yy145;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy177;
	default:	goto yy145;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy178;
	default:	goto yy145;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy179;
	default:	goto yy145;
	}
yy179:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy180;
	}
yy180:
#line 126 "scanner.re2c"
	{ RET(TOKEN_RETURN); }
#line 1585 "scanner.c"
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy182;
	default:	goto yy145;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy183;
	default:	goto yy145;
	}
yy183:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy184;
	}
yy184:
#line 119 "scanner.re2c"
	{ RET(TOKEN_REPEAT); }
#line 1669 "scanner.c"
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy189;
	default:	goto yy145;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy187;
	default:	goto yy145;
	}
yy187:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy188;
	}
yy188:
#line 127 "scanner.re2c"
	{ RET(TOKEN_FUN); }
#line 1753 "scanner.c"
yy189:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy190;
	}
yy190:
#line 118 "scanner.re2c"
	{ RET(TOKEN_FOR); }
#line 1825 "scanner.c"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy192;
	default:	goto yy145;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy193;
	default:	goto yy145;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy194;
	default:	goto yy145;
	}
yy194:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy195;
	}
yy195:
#line 117 "scanner.re2c"
	{ RET(TOKEN_BREAK); }
#line 1915 "scanner.c"
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy208;
	default:	goto yy145;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy145;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy199;
	case 't':	goto yy200;
	default:	goto yy145;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy206;
	default:	goto yy145;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy201;
	default:	goto yy145;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy202;
	default:	goto yy145;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy203;
	default:	goto yy145;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy204;
	default:	goto yy145;
	}
yy204:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy205;
	}
yy205:
#line 123 "scanner.re2c"
	{ RET(TOKEN_CONTINUE); }
#line 2036 "scanner.c"
yy206:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy207;
	}
yy207:
#line 116 "scanner.re2c"
	{ RET(TOKEN_CONST); }
#line 2108 "scanner.c"
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy209;
	default:	goto yy145;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy210;
	default:	goto yy145;
	}
yy210:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy211;
	}
yy211:
#line 129 "scanner.re2c"
	{ RET(TOKEN_CLASS); }
#line 2192 "scanner.c"
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy219;
	default:	goto yy145;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy214;
	default:	goto yy145;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy215;
	default:	goto yy145;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy216;
	default:	goto yy145;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy217;
	default:	goto yy145;
	}
yy217:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy218;
	}
yy218:
#line 115 "scanner.re2c"
	{ RET(TOKEN_STATIC); }
#line 2294 "scanner.c"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy220;
	default:	goto yy145;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy221;
	default:	goto yy145;
	}
yy221:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy222;
	}
yy222:
#line 131 "scanner.re2c"
	{ RET(TOKEN_SPORK); }
#line 2378 "scanner.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy224;
	default:	goto yy145;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy225;
	default:	goto yy145;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy226;
	default:	goto yy145;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy227;
	default:	goto yy145;
	}
yy227:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy144;
	default:	goto yy228;
	}
yy228:
#line 114 "scanner.re2c"
	{ RET(TOKEN_PUBLIC); }
#line 2474 "scanner.c"
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy234;
	default:	goto yy80;
	}
yy230:
	++YYCURSOR;
#line 112 "scanner.re2c"
	{ goto line_comment; }
#line 2485 "scanner.c"
yy232:
	++YYCURSOR;
#line 111 "scanner.re2c"
	{ goto block_comment; }
#line 2490 "scanner.c"
yy234:
	++YYCURSOR;
#line 181 "scanner.re2c"
	{ RET(TOKEN_DIV_CHUCK); }
#line 2495 "scanner.c"
yy236:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy237:
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '"':	goto yy239;
	case '\\':	goto yy238;
	default:	goto yy236;
	}
yy238:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy236;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy242;
	case 'x':	goto yy241;
	default:	goto yy80;
	}
yy239:
	++YYCURSOR;
#line 108 "scanner.re2c"
	{ RET(TOKEN_STRING); }
#line 2539 "scanner.c"
yy241:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	default:	goto yy80;
	}
yy242:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '"':	goto yy239;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy242;
	case '\\':	goto yy238;
	default:	goto yy236;
	}
yy244:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '"':	goto yy239;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy244;
	case '\\':	goto yy238;
	default:	goto yy236;
	}
yy246:
	yyaccept = 13;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy246;
	case 'E':
	case 'e':	goto yy249;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy248:
#line 107 "scanner.re2c"
	{ RET(TOKEN_DOUBLE); }
#line 2648 "scanner.c"
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy251;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy252;
	default:	goto yy80;
	}
yy250:
	yych = *++YYCURSOR;
	goto yy248;
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy252;
	default:	goto yy80;
	}
yy252:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy252;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy254:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy255:
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '\'':	goto yy257;
	case '\\':	goto yy256;
	default:	goto yy254;
	}
yy256:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy254;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy259;
	case 'x':	goto yy258;
	default:	goto yy80;
	}
yy257:
	yych = *++YYCURSOR;
	goto yy3;
yy258:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy261;
	default:	goto yy80;
	}
yy259:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '\'':	goto yy257;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy259;
	case '\\':	goto yy256;
	default:	goto yy254;
	}
yy261:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':	goto yy80;
	case '\'':	goto yy257;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy261;
	case '\\':	goto yy256;
	default:	goto yy254;
	}
yy263:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy274;
	default:	goto yy273;
	}
yy264:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy265:
	switch (yych) {
	case '.':	goto yy263;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy264;
	case 'E':
	case 'e':	goto yy266;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy267;
	default:	goto yy3;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy269;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy270;
	default:	goto yy80;
	}
yy267:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy267;
	default:	goto yy3;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy270;
	default:	goto yy80;
	}
yy270:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy270;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy272:
	yyaccept = 13;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy273:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy272;
	case 'E':
	case 'e':	goto yy278;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy275;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy276;
	default:	goto yy80;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy276;
	default:	goto yy80;
	}
yy276:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy276;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy279;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy280;
	default:	goto yy80;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy280;
	default:	goto yy80;
	}
yy280:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy280;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy250;
	default:	goto yy248;
	}
yy282:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy283:
	switch (yych) {
	case '.':	goto yy263;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy282;
	case 'E':
	case 'e':	goto yy266;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy289;
	default:	goto yy3;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy285;
	default:	goto yy80;
	}
yy285:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy285;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy287;
	default:	goto yy3;
	}
yy287:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy287;
	default:	goto yy3;
	}
yy289:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy289;
	default:	goto yy3;
	}
}
#line 200 "scanner.re2c"


line_comment:

#line 3171 "scanner.c"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy293;
	default:	goto yy295;
	}
yy293:
	++YYCURSOR;
#line 205 "scanner.re2c"
	{
            if(cursor >= scanner->eof) { RET(TOKEN_EOI); }
            scanner->tok = scanner->pos = cursor; scanner->line++;
            goto std;
        }
#line 3188 "scanner.c"
yy295:
	++YYCURSOR;
#line 210 "scanner.re2c"
	{ goto line_comment; }
#line 3193 "scanner.c"
}
#line 211 "scanner.re2c"


block_comment:

#line 3200 "scanner.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy301;
	case '*':	goto yy299;
	default:	goto yy303;
	}
yy299:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy304;
	default:	goto yy300;
	}
yy300:
#line 222 "scanner.re2c"
	{ goto block_comment; }
#line 3219 "scanner.c"
yy301:
	++YYCURSOR;
#line 217 "scanner.re2c"
	{
        if(cursor >= scanner->eof) { RET(TOKEN_EOI); }
        scanner->tok = scanner->pos = cursor; scanner->line++;
        goto block_comment;
        }
#line 3228 "scanner.c"
yy303:
	yych = *++YYCURSOR;
	goto yy300;
yy304:
	++YYCURSOR;
#line 215 "scanner.re2c"
	{ goto std; }
#line 3236 "scanner.c"
}
#line 223 "scanner.re2c"

}

const char *chuck_scanner_token_string(int token)
{
    static BOOL initialised = false;
    static const char *TOKEN_STRINGS[MAX_TOKENS];
    if (!initialised)
    {
        initialised = true;
        TOKEN_STRINGS[TOKEN_EOI] = "EOI";
        TOKEN_STRINGS[TOKEN_ERROR] = "ERROR";
        TOKEN_STRINGS[TOKEN_LOG_AND] = "LOGAND";
        TOKEN_STRINGS[TOKEN_LOG_OR] = "LOGOR";
        TOKEN_STRINGS[TOKEN_LOG_XOR] = "LOGXOR";
        TOKEN_STRINGS[TOKEN_UP_CHUCK] = "UP_CHUCK";
        TOKEN_STRINGS[TOKEN_LSHIFT_CHUCK] = "LSHIFT_CHUCK";
        TOKEN_STRINGS[TOKEN_RSHIFT_CHUCK] = "RSHIFT_CHUCK";
        TOKEN_STRINGS[TOKEN_UN_CHUCK] = "UN_CHUCK";
        TOKEN_STRINGS[TOKEN_MINUS_CHUCK] = "MINUS_CHUCK";
        TOKEN_STRINGS[TOKEN_PLUS_CHUCK] = "PLUS_CHUCK";
        TOKEN_STRINGS[TOKEN_DIV_CHUCK] = "DIV_CHUCK";
        TOKEN_STRINGS[TOKEN_MOD_CHUCK] = "MOD_CHUCK";
        TOKEN_STRINGS[TOKEN_TIMES_CHUCK] = "TIMES_CHUCK";
        TOKEN_STRINGS[TOKEN_LSHIFT_CHUCK] = "LSHIFT_CHUCK";
        TOKEN_STRINGS[TOKEN_RSHIFT_CHUCK] = "RSHIFT_CHUCK";
        TOKEN_STRINGS[TOKEN_BIT_AND_CHUCK] = "BIT_AND_CHUCK";
        TOKEN_STRINGS[TOKEN_BIT_OR_CHUCK] = "BIT_OR_CHUCK";
        TOKEN_STRINGS[TOKEN_BIT_XOR_CHUCK] = "BIT_XOR_CHUCK";
        TOKEN_STRINGS[TOKEN_BIT_NOT_CHUCK] = "BIT_NOT_CHUCK";
        TOKEN_STRINGS[TOKEN_AT_CHUCK] = "AT_CHUCK";
        TOKEN_STRINGS[TOKEN_PLUS] = "PLUS";
        TOKEN_STRINGS[TOKEN_MINUS] = "MINUS";
        TOKEN_STRINGS[TOKEN_TIMES] = "TIMES";
        TOKEN_STRINGS[TOKEN_DIVIDE] = "DIVIDE";
        TOKEN_STRINGS[TOKEN_PERCENT] = "PERCENT";
        TOKEN_STRINGS[TOKEN_BIT_AND] = "BIT_AND";
        TOKEN_STRINGS[TOKEN_BIT_OR] = "BIT_OR";
        TOKEN_STRINGS[TOKEN_BIT_XOR] = "BIT_XOR";
        TOKEN_STRINGS[TOKEN_LSHIFT] = "LSHIFT";
        TOKEN_STRINGS[TOKEN_RSHIFT] = "RSHIFT";
        TOKEN_STRINGS[TOKEN_LSQUARE] = "LSQUARE";
        TOKEN_STRINGS[TOKEN_COLONCOLON] = "COLONCOLON";
        TOKEN_STRINGS[TOKEN_LBRACE] = "LBRACE";
        TOKEN_STRINGS[TOKEN_RBRACE] = "RBRACE";
        TOKEN_STRINGS[TOKEN_BREAK] = "BREAK";
        TOKEN_STRINGS[TOKEN_SEMICOLON] = "SEMICOLON";
        TOKEN_STRINGS[TOKEN_CONTINUE] = "CONTINUE";
        TOKEN_STRINGS[TOKEN_LTLTLT] = "LTLTLT";
        TOKEN_STRINGS[TOKEN_GTGTGT] = "GTGTGT";
        TOKEN_STRINGS[TOKEN_RETURN] = "RETURN";
        TOKEN_STRINGS[TOKEN_FOR] = "FOR";
        TOKEN_STRINGS[TOKEN_LPAREN] = "LPAREN";
        TOKEN_STRINGS[TOKEN_RPAREN] = "RPAREN";
        TOKEN_STRINGS[TOKEN_IF] = "IF";
        TOKEN_STRINGS[TOKEN_ELSE] = "ELSE";
        TOKEN_STRINGS[TOKEN_CONST] = "CONST";
        TOKEN_STRINGS[TOKEN_PUBLIC] = "PUBLIC";
        TOKEN_STRINGS[TOKEN_STATIC] = "STATIC";
        TOKEN_STRINGS[TOKEN_REPEAT] = "REPEAT";
        TOKEN_STRINGS[TOKEN_WHILE] = "WHILE";
        TOKEN_STRINGS[TOKEN_UNTIL] = "UNTIL";
        TOKEN_STRINGS[TOKEN_DO] = "DO";
        TOKEN_STRINGS[TOKEN_SPORK] = "SPORK";
        TOKEN_STRINGS[TOKEN_TILDE] = "TILDE";
        TOKEN_STRINGS[TOKEN_IDENTIFIER] = "IDENTIFIER";
        TOKEN_STRINGS[TOKEN_AT] = "AT";
        TOKEN_STRINGS[TOKEN_STATIC] = "STATIC";
        TOKEN_STRINGS[TOKEN_DOLLAR] = "DOLLAR";
        TOKEN_STRINGS[TOKEN_RSQUARE] = "RSQUARE";
        TOKEN_STRINGS[TOKEN_CHUCK] = "CHUCK";
        TOKEN_STRINGS[TOKEN_NOT_CHUCK] = "NOT_CHUCK";
        TOKEN_STRINGS[TOKEN_POWER] = "POWER";
        TOKEN_STRINGS[TOKEN_CMP_LE] = "CMP_LE";
        TOKEN_STRINGS[TOKEN_CMP_LT] = "CMP_LT";
        TOKEN_STRINGS[TOKEN_CMP_EQ] = "CMP_EQ";
        TOKEN_STRINGS[TOKEN_CMP_NE] = "CMP_NE";
        TOKEN_STRINGS[TOKEN_CMP_GT] = "CMP_GT";
        TOKEN_STRINGS[TOKEN_CMP_GE] = "CMP_GE";
        TOKEN_STRINGS[TOKEN_LOG_AND] = "LOG_AND";
        TOKEN_STRINGS[TOKEN_LOG_OR] = "LOG_OR";
        TOKEN_STRINGS[TOKEN_LOG_XOR] = "LOG_XOR";
        TOKEN_STRINGS[TOKEN_PLUSPLUS] = "PLUSPLUS";
        TOKEN_STRINGS[TOKEN_MINUSMINUS] = "MINUSMINUS";
        TOKEN_STRINGS[TOKEN_BIT_NOT] = "BIT_NOT";
        TOKEN_STRINGS[TOKEN_NOT] = "NOT";
        TOKEN_STRINGS[TOKEN_DOT] = "DOT";
        TOKEN_STRINGS[TOKEN_NEW] = "NEW";
        TOKEN_STRINGS[TOKEN_LONG] = "LONG";
        TOKEN_STRINGS[TOKEN_DOUBLE] = "DOUBLE";
        TOKEN_STRINGS[TOKEN_STRING] = "STRING";
        TOKEN_STRINGS[TOKEN_HASH] = "HASH";
        TOKEN_STRINGS[TOKEN_COMMA] = "COMMA";
        TOKEN_STRINGS[TOKEN_CLASS] = "CLASS";
        TOKEN_STRINGS[TOKEN_EXTENDS] = "EXTENDS";
        TOKEN_STRINGS[TOKEN_FUN] = "FUN";
    }
    return TOKEN_STRINGS[token];
}
